version: 1.0.{build}
image: Visual Studio 2017
install:
  - dotnet tool install fake-cli -g
  - dotnet tool install coverlet.console -g
  - choco install --no-progress codecov -y
  - choco install --no-progress gitversion.portable -y
before_build:
  - ps: gitversion /output buildserver 
build_script:
- ps: >-
    fake run Build.fsx -p 3
test: off